### PR TITLE
Export macros

### PR DESCRIPTION
**Pull request by jojolepro**

### CODE REVIEW

**Comment by WaDelma** [comment]
These were public before, but I removed them as they were not that useful for outside the crate and I created the custom derive that are more usable.

So I am asking where are these useful? Just wondering what is the use case.

**Comment by WaDelma** [comment]
Ah these are actually different macros, never mind then :D

**Comment by jojolepro** [comment]
image

**Comment by jojolepro** [comment]
I end up solving my use case by copy pasting the macros and replacing the types by my own. Only the two macros in the lattice file could be used as-is, so I'm closing this pr. Thanks for checking it out!

**Pull request closed without merging**
