### PR TITLE
Added is_finite method for Real

### PR DESCRIPTION
**Pull request by jojolepro**
<3

### CODE REVIEW

**Comment by jojolepro** [comment]
@sebcrozet can this be merged?

**Comment by sebcrozet** [comment]
@jojolepro Thanks! Sorry for the late answer. Could you provide an explanation about why this is needed? What is your specific use-case?

Also the `Default` super-trait should not be added without justification as well. `Default` makes very little sense for a real number which has two neutral elements (0 and 1). 

This is a breaking change.

**Comment by jojolepro** [comment]
Ah true I didn't think much of the Default.

The reason for the addition of is_finite is to allow checking if a N is finite, without having to use feature gates to know if we should be checking for f32::is_nan and f64::is_nan. It will be used in the amethyst engine, inside of the `Transform` component.
Usage example:
```rs
    /// Verifies that the global `Matrix4` doesn't contain any NaN values.
    pub fn is_finite(&self) -> bool {
        self.global_matrix.as_slice().iter().all(|f| f32::is_finite(*f))
    }
```

**Comment by sebcrozet** [comment]
@jojolepro Thank you for the clarification. Because this is a breaking change, this will be released under the version 0.9 (which will not happen immediatly).

**Pull request merged**
